# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: checkout/checkout@v3

      - name: Set up Go
        uses: checkout/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        run: make init test