name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        with:
          platforms: linux/amd64

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-buildx-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build binaries
        run: make docker-release

      - name: Archive binaries
        run: |
          mkdir -p release
          mv _output/*.tar.gz release/

      - name: Read Version from File
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Read CHANGELOG from File
        id: read_changelog
        run: |
          CHANGELOG_CONTENT=$(cat CHANGELOG/`cat VERSION`.md)
          echo "CHANGELOG=$CHANGELOG_CONTENT" >> $GITHUB_ENV

      - name: Write CHANGELOG to file
        run: echo "${{ env.CHANGELOG }}" > release/CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          draft: false
          prerelease: false
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: release/CHANGELOG.txt
#          body: ${{ env.CHANGELOG }}